force-app/main/default/objects/ETF__c/ETF__c.object-meta.xml
<CustomObject>
    <description>An Exchange Traded Fund (ETF) is a market linked investment that tracks a specific index, sector, commodity, or asset class. For example, an ETF tracking the Nifty 50 will invest in the same 50 companies in the same proportion as the index.</description>
    <label>Exchange Traded Fund</label>
    <nameField>
        <label>ETF</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exchange Traded Funds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ETF__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <inlineHelpText>Represents the percentage of the total investment amount allocated to this ETF.</inlineHelpText>
    <label>Allocation (%)</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ETF__c/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <description>Indicates based on the geographic focus of its underlying holdings.</description>
    <label>Market</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETF__c/fields/Stock_Exchange__c.field-meta.xml
<CustomField>
    <fullName>Stock_Exchange__c</fullName>
    <description>A stock exchange is a marketplace where stockbrokers and traders can buy and sell securities, such as shares of stock, bonds and other financial instruments.</description>
    <label>Stock Exchange</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bombay Stock Exchange (BSE)</fullName>
            </value>
            <value>
                <fullName>National Stock Exchange of India (NSE)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ETF__c/fields/Ticker_Symbol__c.field-meta.xml
<CustomField>
    <fullName>Ticker_Symbol__c</fullName>
    <inlineHelpText>It is a unique series of letters or numbers used to identify publicly traded shares of a company on a stock exchange.</inlineHelpText>
    <label>Ticker Symbol</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Investment__c/Investment__c.object-meta.xml
<CustomObject>
    <description>This Object stores the details of the Investment on monthly/yearly/days basis.</description>
    <label>Investment</label>
    <nameField>
        <label>Investment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Investments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Investment__c/fields/Allocation__c.field-meta.xml
<CustomField>
    <fullName>Allocation__c</fullName>
    <label>Allocation %</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/ETF__c.field-meta.xml
<CustomField>
    <fullName>ETF__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exchange Traded Fund (ETF)</label>
    <referenceTo>ETF__c</referenceTo>
    <relationshipLabel>Investments</relationshipLabel>
    <relationshipName>Investments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Investment__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nippon India ETF Nifty 50 BeES (NIFTYBEES)</fullName>
            </value>
            <value>
                <fullName>Nippon India ETF Nifty Midcap 150 (MID150BEES)</fullName>
            </value>
            <value>
                <fullName>HDFC NIFTY Smallcap 250 ETF (HDFCSML250)</fullName>
            </value>
            <value>
                <fullName>Nippon India ETF Gold BeES (GOLDBEES)</fullName>
            </value>
            <value>
                <fullName>Mirae Asset S&amp;P 500 Top 50 ETF (MASPTOP50)</fullName>
            </value>
            <value>
                <fullName>Motilal Oswal MOSt Shares NASDAQ-100 ETF (MON100)</fullName>
            </value>
            <value>
                <fullName>Mirae Asset NYSE FANG+ ETF (MAFANG)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Investment__c/recordTypes/ETF_Investment.recordType-meta.xml
<RecordType>
    <fullName>ETF_Investment</fullName>
    <active>true</active>
    <description>This Record Type is used for all the Exchange Traded Fund (ETF) investments.</description>
    <label>ETF Investment</label>
</RecordType>

force-app/main/default/classes/LinkInvestmentsToETFLookup.cls
public class LinkInvestmentsToETFLookup {

    // This method updates the existing ETF Investment__c records with the corresponding ETF__c lookup value
    public static void linkInvestmentsToETF() {
        Map<String, Id> etfToIdMap = new Map<String, Id>();
        List<Investment__c> invRecsToUpdate = new List<Investment__c>();

        for(ETF__c etf: [SELECT Id, Name, Ticker_Symbol__c, Stock_Exchange__c, Market__c, Allocation__c FROM ETF__c]) {
            etfToIdMap.put(etf.Name, etf.Id);
        }

        for(Investment__c invRec : [SELECT Id, Name, Name__c, ETF__c FROM Investment__c WHERE RecordType.DeveloperName = 'ETF_Investment']) {
            Investment__c inv = new Investment__c(Id = invRec.Id);
            String etfName = invRec.Name__c;
            String etf = String.isNotBlank(etfName) ? etfName.substring(0, etfName.indexof('(')-1).trim() : null;	
            
            if(String.isNotBlank(etf)) {
                inv.ETF__c = etfToIdMap.get(etf);
                invRecsToUpdate.add(inv);
            }
        }

        if(!invRecsToUpdate.isEmpty()) {
            update invRecsToUpdate;
        }
    }
}